In [1]:
import torch

In [2]:
device ='cuda' if torch.cuda.is_available() else 'cpu'

In [3]:
device

'cuda'

In [4]:
#new array create
newarray=torch.tensor([[1,2,3],[2,3,4]],dtype=torch.float32,device=device,requires_grad=True)

In [5]:
newarray

tensor([[1., 2., 3.],
        [2., 3., 4.]], device='cuda:0', requires_grad=True)

In [6]:
newarray.dtype

torch.float32

In [7]:
newarray.device

device(type='cuda', index=0)

In [8]:
newarray.requires_grad

True

# *Array*

In [9]:
#random array
randomarray=torch.rand((2,3))

In [10]:
randomarray

tensor([[0.8581, 0.1606, 0.4638],
        [0.4779, 0.3223, 0.3615]])

In [11]:
#eyes array
eyearray=torch.eye(3,3)

In [12]:
eyearray

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [13]:
#zero array
zeroarray=torch.zeros((2,2))

In [14]:
zeroarray

tensor([[0., 0.],
        [0., 0.]])

In [15]:
#ones array
onesarray=torch.ones((3,3))

In [16]:
onesarray

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [17]:
#arrange array
arrangearra=torch.arange(start=0,end=11,step=2)

In [18]:
arrangearra

tensor([ 0,  2,  4,  6,  8, 10])

In [19]:
#linespace
linespance=torch.linspace(start=0.1,end=5,steps=5)

In [20]:
linespance

tensor([0.1000, 1.3250, 2.5500, 3.7750, 5.0000])

In [21]:
#tensor
tensor=torch.arange(4)

In [22]:
tensor


tensor([0, 1, 2, 3])

# *Take two 4 dimension array and multiply them*

In [24]:
#array1 x4
x4=torch.rand((4,4),dtype=torch.float32)
x4

tensor([[0.7281, 0.4895, 0.8981, 0.3889],
        [0.7916, 0.9143, 0.6675, 0.7807],
        [0.1788, 0.9507, 0.2823, 0.2323],
        [0.0778, 0.5555, 0.5934, 0.7563]])

In [25]:
#array2 y4
y4=torch.rand((4,4),dtype=torch.float32)
y4

tensor([[0.1721, 0.8328, 0.3409, 0.2039],
        [0.3362, 0.7312, 0.8135, 0.8689],
        [0.4295, 0.9668, 0.2497, 0.7448],
        [0.7009, 0.4146, 0.6542, 0.4214]])

In [26]:
#multiply x4 and y4
x4*y4

tensor([[0.1253, 0.4076, 0.3061, 0.0793],
        [0.2661, 0.6685, 0.5430, 0.6784],
        [0.0768, 0.9192, 0.0705, 0.1730],
        [0.0545, 0.2303, 0.3882, 0.3187]])

In [27]:
#if y4=0
y4=torch.zeros(4,4)

In [29]:
#result
x4*y4

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])