In [11]:
import torch

# ***Create Tensor***

In [4]:
x = torch.randn(3)
print(x)

tensor([ 0.0675, -0.6619,  0.0738])


In [6]:
#Requires Gradient
x = torch.randn(3, requires_grad=True)
print(x)

tensor([-0.6027,  0.3371,  2.2096], requires_grad=True)


In [8]:
#Adding with backpropagation
x = torch.randn(3, requires_grad=True)
print(x)

y= x+2
print(y)

tensor([-0.7231, -0.6232, -0.4043], requires_grad=True)
tensor([1.2769, 1.3768, 1.5957], grad_fn=<AddBackward0>)


In [10]:
#Mean backward gradient function
x = torch.randn(3, requires_grad=True)
print(x)

y= x+2
print(y)

z=y*y*2
z= z.mean()
print(z)

tensor([ 1.5909, -0.2851, -1.6028], requires_grad=True)
tensor([3.5909, 1.7149, 0.3972], grad_fn=<AddBackward0>)
tensor(10.6619, grad_fn=<MeanBackward0>)


In [6]:
#Gradient of the tensors
x = torch.randn(3, requires_grad=True)
print(x)

y= x+2
print(y)

z=y*y*2
z= z.mean()
print(z)

z.backward() #dz/dx
print(x.grad)

tensor([-1.7688,  0.9635, -0.4635], requires_grad=True)
tensor([0.2312, 2.9635, 1.5365], grad_fn=<AddBackward0>)
tensor(7.4642, grad_fn=<MeanBackward0>)
tensor([0.3082, 3.9513, 2.0487])


***How we can stop by touch from creating this gradient functions***

In [9]:
#same value but doesn't require gradient
x= torch.randn(3, requires_grad=True)
print(x)

#x.requires_grad_(False)
#x.detach()
#with torch.no_grad():
y=x.detach()
print(y)


tensor([ 0.1824,  0.9654, -0.1044], requires_grad=True)
tensor([ 0.1824,  0.9654, -0.1044])


In [12]:
with torch.no_grad():
  y = x+2
  print(y)

tensor([2.1824, 2.9654, 1.8956])


In [13]:
#Training Example

weights = torch.ones(4, requires_grad=True)

for epoch in range(1):
  model_output = (weights*3).sum()

  model_output.backward()
print(weights.grad)


tensor([3., 3., 3., 3.])


In [16]:
#Iteration 2
weights = torch.ones(4, requires_grad=True)

for epoch in range(2):
  model_output = (weights*3).sum()

  model_output.backward()
print(weights.grad)


tensor([6., 6., 6., 6.])


In [19]:
#Iteration 3
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
  model_output = (weights*3).sum()

  model_output.backward()
print(weights.grad)

tensor([9., 9., 9., 9.])


In [20]:
#Correct Gradients

weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
  model_output = (weights*3).sum()

  model_output.backward()
print(weights.grad)
weights.grad.zero_()

tensor([9., 9., 9., 9.])


tensor([0., 0., 0., 0.])