# ***Import Library***

In [2]:
import torch
import numpy as np

In [13]:
#empty tensor
x= torch.empty(1)
print(x)

tensor([nan])


In [ ]:
#3 elements
x= torch.empty(3)
print(x)

tensor([ 3.3631e-44,  0.0000e+00, -7.5866e-13])


In [ ]:
#2D
x= torch.empty(2, 3)
print(x)

tensor([[3.1458e+06, 3.2175e-41, 3.7828e+08],
        [3.2175e-41, 8.9683e-44, 0.0000e+00]])


In [ ]:
#3D
x= torch.empty(2,2,3)
print(x)

tensor([[[3.7822e+08, 3.2175e-41, 3.7901e+08],
         [3.2175e-41, 8.9683e-44, 0.0000e+00]],

        [[4.5447e+30, 7.0062e+22, 2.1707e-18],
         [1.9284e+31, 3.2314e-18, 2.3592e-09]]])


In [ ]:
#random values
x = torch.rand(2,2)
print(x)

tensor([[0.9994, 0.1172],
        [0.6582, 0.0627]])


In [ ]:
#zero 2D

x=torch.ones(2,2)

In [ ]:
#data type show

x= torch.ones(2,2,dtype=torch.double)
print(x)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


In [ ]:
#size
x= torch.ones(2,2,dtype=torch.float16)
print(x.size())

torch.Size([2, 2])


In [ ]:
#Tensor data

x=torch.tensor([2.5, 0.1])
print(x)

tensor([2.5000, 0.1000])


# ***Basic Operations***




In [ ]:
#2 random values

x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

tensor([[0.8965, 0.0575],
        [0.9406, 0.2247]])
tensor([[0.0614, 0.8053],
        [0.5103, 0.4302]])


In [ ]:
#2 random values + addition

x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

z=x+y #or z=torch.add(x,y)
print(z)

tensor([[0.8825, 0.2091],
        [0.1154, 0.0370]])
tensor([[0.0559, 0.8449],
        [0.9389, 0.6598]])
tensor([[0.9384, 1.0540],
        [1.0543, 0.6968]])


In [ ]:
#substraction
x= torch.rand(2,2)
y= torch.rand(2,2)

z= x-y
z= torch.sub(x,y)
print(z)


tensor([[-0.0213,  0.7482],
        [ 0.2777,  0.4371]])


In [ ]:
#multiplication
x= torch.rand(2,2)
y= torch.rand(2,2)

z= x*y
z= torch.mul(x,y)
print(z)


tensor([[0.2733, 0.1153],
        [0.3276, 0.4272]])


In [ ]:
#division
x= torch.rand(2,2)
y= torch.rand(2,2)

z= x/y
z= torch.div(x,y)
print(z)

tensor([[0.2055, 0.9010],
        [0.3713, 0.3039]])


In [ ]:
#5*3 MATRIX
x=torch.rand(5,3)
print(x)

tensor([[0.5245, 0.9976, 0.1671],
        [0.9164, 0.1561, 0.2266],
        [0.8346, 0.8976, 0.2103],
        [0.2838, 0.4112, 0.6271],
        [0.8156, 0.0910, 0.5473]])


In [2]:
#Print only first column of all the rows
x = torch.rand(5,3)
print(x)
print(x[:,0])

tensor([[0.0853, 0.4062, 0.4865],
        [0.3774, 0.9645, 0.9691],
        [0.6608, 0.1683, 0.3250],
        [0.5250, 0.2456, 0.1007],
        [0.7117, 0.1020, 0.3966]])
tensor([0.0853, 0.3774, 0.6608, 0.5250, 0.7117])


In [3]:
#Print row no. 1 of all columns
x= torch.rand(5,3)
print(x)
print(x[1,:])

tensor([[0.3685, 0.9064, 0.9709],
        [0.3110, 0.9192, 0.5344],
        [0.5504, 0.7250, 0.8958],
        [0.3839, 0.2752, 0.7874],
        [0.0569, 0.9192, 0.1801]])
tensor([0.3110, 0.9192, 0.5344])


In [4]:
#Print 1:1
x= torch.rand(5,3)
print(x)
print(x[1,1])

tensor([[0.7670, 0.3396, 0.9003],
        [0.8958, 0.2317, 0.4047],
        [0.3805, 0.7716, 0.6705],
        [0.2470, 0.2310, 0.0157],
        [0.6658, 0.4753, 0.2798]])
tensor(0.2317)


In [5]:
#Print 1:1 (Actual value)
x= torch.rand(5,3)
print(x)
print(x[1,1].item())

tensor([[0.2490, 0.9675, 0.4638],
        [0.5382, 0.9990, 0.8346],
        [0.7419, 0.1980, 0.2470],
        [0.6210, 0.3774, 0.2219],
        [0.7451, 0.0859, 0.8273]])
0.999015748500824


In [6]:
#Reshaping (All the values of the 4*4 matrix)

x = torch.rand(4,4)
print(x)
y = x.view(16)
print(y)

tensor([[0.0831, 0.7100, 0.2570, 0.8998],
        [0.2881, 0.3957, 0.5272, 0.6656],
        [0.7263, 0.4664, 0.5188, 0.6005],
        [0.7361, 0.0928, 0.6418, 0.7076]])
tensor([0.0831, 0.7100, 0.2570, 0.8998, 0.2881, 0.3957, 0.5272, 0.6656, 0.7263,
        0.4664, 0.5188, 0.6005, 0.7361, 0.0928, 0.6418, 0.7076])


In [7]:
#Resize Tensor

x = torch.rand(4,4)
print(x)
y = x.view(-1,8)
print(y.size())

tensor([[0.2470, 0.2712, 0.6828, 0.1985],
        [0.4773, 0.5751, 0.0451, 0.9249],
        [0.5562, 0.4954, 0.5343, 0.8004],
        [0.0024, 0.1484, 0.2208, 0.7044]])
torch.Size([2, 8])


# ***numpy to torch tensor and vice versa***

In [3]:
#numpy to torch tensor and vice versa
x=torch.ones(5)
print(x)
y= x.numpy()
print(y)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [4]:
#adding 1 with elemenets
x=torch.ones(5)
print(x)
y= x.numpy()
print(y)

x.add_(1) #Underscore means adding 1 with all elements
print(x)
print(y)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [6]:
#datatype showing
x = np.ones(5)
print(x)
y= torch.from_numpy(x)
print(y)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [8]:
#datatype showing (modify by adding +1)
x = np.ones(5)
print(x)
y= torch.from_numpy(x)
print(y)

x+=1
print(x)
print(y)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [10]:
#Cuda toolkit
if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.ones(5, device=device)
  y = torch.ones(5)
  y = y.to(device)
  z = x+y
  z = z.to("cpu")
  print(z)

tensor([2., 2., 2., 2., 2.])


# ***Calculate gradient for tensors***

In [12]:
x= torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
