In [1]:
import torch
import numpy as np

# ***Initialize Tensor***

In [ ]:
#list
data = [[1,2],[3,4]]
x_data = torch.tensor(data) #convert in tensor
x_data #object lookup

tensor([[1, 2],
        [3, 4]])

# **From numpy array**

In [ ]:
np_array = np.array(data)
np_array

array([[1, 2],
       [3, 4]])

In [ ]:
#n dimensional array
np_array = np.array(data)
x_np = torch.from_numpy(np_array) #numpy to tensor
type(np_array)

numpy.ndarray

In [ ]:
#Initialize from another tensor
#2D array with 1
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [ ]:
#random number
x_ones = torch.ones_like(x_data)
x_rand = torch.rand_like(x_data,dtype=torch.float)
x_rand

tensor([[0.5532, 0.9356],
        [0.2901, 0.3725]])

In [ ]:
shape = (3,5)
rand_tensor = torch.rand(shape)

rand_tensor

tensor([[0.9460, 0.8643, 0.1436, 0.3698, 0.0583],
        [0.3861, 0.2622, 0.4698, 0.3401, 0.3825],
        [0.2026, 0.4672, 0.3289, 0.8134, 0.1641]])

In [ ]:
#initialize in 1's
shape = (3,5)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)

ones_tensor

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
#initialize in 0's
shape = (3,5)
rand_tensor = torch.rand(shape)
zeros_tensor = torch.zeros(shape)

zeros_tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

# ***Attributes of a Tensor***

In [2]:
tensor = torch.rand(5,7)
tensor.device

device(type='cpu')

# ***Operations of tensors***

In [3]:
device = 'cpu'
if torch.cuda.is_available():
    device = 'cuda'
device

'cuda'

In [4]:
tensor = torch.rand(5,7)
print(tensor.device)
tensor = tensor.to(device)
print(tensor.device)

cpu
cuda:0


In [5]:
#standard numpy-like indexing and slicing:
tensor = torch.rand(5,7)
tensor = tensor.to(device)

print(tensor)
print(tensor[:,0])

tensor([[0.3482, 0.4376, 0.3442, 0.9032, 0.1666, 0.9878, 0.1325],
        [0.2760, 0.7601, 0.6519, 0.9442, 0.5452, 0.0956, 0.9264],
        [0.0892, 0.8619, 0.2184, 0.8961, 0.4670, 0.0850, 0.1576],
        [0.5530, 0.8319, 0.0919, 0.2493, 0.5181, 0.7789, 0.1865],
        [0.0995, 0.0132, 0.2368, 0.8860, 0.3898, 0.5012, 0.3953]],
       device='cuda:0')
tensor([0.3482, 0.2760, 0.0892, 0.5530, 0.0995], device='cuda:0')


In [6]:
#check the last column
tensor = torch.rand(5,7)
tensor = tensor.to(device)

print(tensor)
print(tensor[:,-1])

tensor([[0.6490, 0.5064, 0.4304, 0.7809, 0.9722, 0.3133, 0.1405],
        [0.5837, 0.7631, 0.5909, 0.8367, 0.2762, 0.8227, 0.2728],
        [0.3704, 0.8872, 0.8393, 0.6311, 0.0694, 0.2588, 0.7297],
        [0.7201, 0.8896, 0.7533, 0.7865, 0.6871, 0.3177, 0.7794],
        [0.5022, 0.2240, 0.1796, 0.0763, 0.3637, 0.0327, 0.8018]],
       device='cuda:0')
tensor([0.1405, 0.2728, 0.7297, 0.7794, 0.8018], device='cuda:0')


In [ ]:
#concatenate
t1 = torch.cat([tensor,tensor])
t1

tensor([[0.3997, 0.5951, 0.5661, 0.8953, 0.1826, 0.5693, 0.2010],
        [0.4515, 0.4324, 0.3541, 0.3093, 0.5065, 0.6188, 0.2166],
        [0.9401, 0.2479, 0.4617, 0.1112, 0.1550, 0.9328, 0.0825],
        [0.3814, 0.0078, 0.1915, 0.9628, 0.5383, 0.6886, 0.1747],
        [0.8901, 0.6594, 0.6485, 0.7899, 0.5761, 0.6093, 0.7770],
        [0.3997, 0.5951, 0.5661, 0.8953, 0.1826, 0.5693, 0.2010],
        [0.4515, 0.4324, 0.3541, 0.3093, 0.5065, 0.6188, 0.2166],
        [0.9401, 0.2479, 0.4617, 0.1112, 0.1550, 0.9328, 0.0825],
        [0.3814, 0.0078, 0.1915, 0.9628, 0.5383, 0.6886, 0.1747],
        [0.8901, 0.6594, 0.6485, 0.7899, 0.5761, 0.6093, 0.7770]])

In [ ]:
#dimension define concatenate
t1 = torch.cat([tensor,tensor], dim=1)
t1

tensor([[0.3997, 0.5951, 0.5661, 0.8953, 0.1826, 0.5693, 0.2010, 0.3997, 0.5951,
         0.5661, 0.8953, 0.1826, 0.5693, 0.2010],
        [0.4515, 0.4324, 0.3541, 0.3093, 0.5065, 0.6188, 0.2166, 0.4515, 0.4324,
         0.3541, 0.3093, 0.5065, 0.6188, 0.2166],
        [0.9401, 0.2479, 0.4617, 0.1112, 0.1550, 0.9328, 0.0825, 0.9401, 0.2479,
         0.4617, 0.1112, 0.1550, 0.9328, 0.0825],
        [0.3814, 0.0078, 0.1915, 0.9628, 0.5383, 0.6886, 0.1747, 0.3814, 0.0078,
         0.1915, 0.9628, 0.5383, 0.6886, 0.1747],
        [0.8901, 0.6594, 0.6485, 0.7899, 0.5761, 0.6093, 0.7770, 0.8901, 0.6594,
         0.6485, 0.7899, 0.5761, 0.6093, 0.7770]])

# ***Arithmetic Operations***

In [7]:
y1 = tensor @ tensor.T #T means gets the transpose of the tensor
y1.shape

torch.Size([5, 5])

In [10]:
#or another way for calling matrix mult.
y1 = tensor @ tensor.T
y1.shape
y1 = tensor.matmul(tensor.T)

torch.matmul(tensor,tensor.T,out=y1)

tensor([[2.5357, 2.2375, 1.7948, 2.7332, 1.0527],
        [2.2375, 2.7998, 2.3483, 2.8661, 0.9802],
        [1.7948, 2.3483, 2.6312, 2.8832, 1.2025],
        [2.7332, 2.8661, 2.8832, 3.6765, 1.6414],
        [1.0527, 0.9802, 1.2025, 1.6414, 1.1167]], device='cuda:0')

In [13]:
#elemnet wise matmul
y1 = tensor @ tensor.T
y1.shape
y1 = tensor.matmul(tensor.T)

torch.matmul(tensor,tensor.T,out=y1)

z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)

torch.mul(tensor,tensor,out=z3)

tensor([[0.4212, 0.2564, 0.1852, 0.6099, 0.9451, 0.0982, 0.0197],
        [0.3408, 0.5822, 0.3492, 0.7001, 0.0763, 0.6768, 0.0744],
        [0.1372, 0.7871, 0.7044, 0.3983, 0.0048, 0.0670, 0.5325],
        [0.5185, 0.7914, 0.5675, 0.6186, 0.4721, 0.1009, 0.6075],
        [0.2522, 0.0502, 0.0323, 0.0058, 0.1323, 0.0011, 0.6429]],
       device='cuda:0')

In [16]:
#Global Aggregession

agg = tensor.sum()
agg_item = agg.item()
agg_item

18.838586807250977

In [17]:
print(tensor)
tensor.add_(1)

tensor([[0.6490, 0.5064, 0.4304, 0.7809, 0.9722, 0.3133, 0.1405],
        [0.5837, 0.7631, 0.5909, 0.8367, 0.2762, 0.8227, 0.2728],
        [0.3704, 0.8872, 0.8393, 0.6311, 0.0694, 0.2588, 0.7297],
        [0.7201, 0.8896, 0.7533, 0.7865, 0.6871, 0.3177, 0.7794],
        [0.5022, 0.2240, 0.1796, 0.0763, 0.3637, 0.0327, 0.8018]],
       device='cuda:0')


tensor([[1.6490, 1.5064, 1.4304, 1.7809, 1.9722, 1.3133, 1.1405],
        [1.5837, 1.7631, 1.5909, 1.8367, 1.2762, 1.8227, 1.2728],
        [1.3704, 1.8872, 1.8393, 1.6311, 1.0694, 1.2588, 1.7297],
        [1.7201, 1.8896, 1.7533, 1.7865, 1.6871, 1.3177, 1.7794],
        [1.5022, 1.2240, 1.1796, 1.0763, 1.3637, 1.0327, 1.8018]],
       device='cuda:0')

# ***Bridge with numpy***

Tensor to NumPy array

In [20]:
tensor = tensor.to('cpu')
n = tensor.numpy()
n

array([[1.6489875, 1.506378 , 1.430376 , 1.7809309, 1.9721563, 1.3133011,
        1.1404877],
       [1.5837421, 1.763051 , 1.590944 , 1.8366942, 1.2761862, 1.822664 ,
        1.2728182],
       [1.3704386, 1.8871831, 1.8392572, 1.6310871, 1.0694358, 1.2587731,
        1.7297072],
       [1.7200725, 1.8895813, 1.7533314, 1.7865207, 1.6870762, 1.3176675,
        1.7794142],
       [1.5022349, 1.2239527, 1.1796087, 1.0763142, 1.363676 , 1.0327041,
        1.8018324]], dtype=float32)

In [22]:
print(tensor)
print(n)

tensor([[1.6490, 1.5064, 1.4304, 1.7809, 1.9722, 1.3133, 1.1405],
        [1.5837, 1.7631, 1.5909, 1.8367, 1.2762, 1.8227, 1.2728],
        [1.3704, 1.8872, 1.8393, 1.6311, 1.0694, 1.2588, 1.7297],
        [1.7201, 1.8896, 1.7533, 1.7865, 1.6871, 1.3177, 1.7794],
        [1.5022, 1.2240, 1.1796, 1.0763, 1.3637, 1.0327, 1.8018]])
[[1.6489875 1.506378  1.430376  1.7809309 1.9721563 1.3133011 1.1404877]
 [1.5837421 1.763051  1.590944  1.8366942 1.2761862 1.822664  1.2728182]
 [1.3704386 1.8871831 1.8392572 1.6310871 1.0694358 1.2587731 1.7297072]
 [1.7200725 1.8895813 1.7533314 1.7865207 1.6870762 1.3176675 1.7794142]
 [1.5022349 1.2239527 1.1796087 1.0763142 1.363676  1.0327041 1.8018324]]


In [24]:
#change tensor
tensor.add_(5)
print(tensor)
print(n)

tensor([[11.6490, 11.5064, 11.4304, 11.7809, 11.9722, 11.3133, 11.1405],
        [11.5837, 11.7631, 11.5909, 11.8367, 11.2762, 11.8227, 11.2728],
        [11.3704, 11.8872, 11.8393, 11.6311, 11.0694, 11.2588, 11.7297],
        [11.7201, 11.8896, 11.7533, 11.7865, 11.6871, 11.3177, 11.7794],
        [11.5022, 11.2240, 11.1796, 11.0763, 11.3637, 11.0327, 11.8018]])
[[11.648988 11.506378 11.430376 11.780931 11.972157 11.313301 11.140488]
 [11.583742 11.763051 11.590944 11.836695 11.276186 11.822664 11.272818]
 [11.370439 11.887183 11.839257 11.631087 11.069436 11.258773 11.729708]
 [11.720073 11.889582 11.753331 11.786521 11.687077 11.317667 11.779414]
 [11.502235 11.223953 11.179609 11.076314 11.363676 11.032704 11.801832]]


*Numpy array to Tensor*

In [27]:
#ndarray
n = np.ones(5)
n

array([1., 1., 1., 1., 1.])

In [28]:
#tensor
t = torch.from_numpy(n)
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)